name: Pre-Release
on:
  push:
    branches:
      - "master"
jobs:
  pre-release-python-jose-job:
    runs-on: ubuntu-latest
    name: pre-release python-jose
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools packaging twine build --upgrade
    - name: Set version number
      run: python update_version_from_git.py
    - name: Build
      run: python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.6
      with:
        skip-existing: true
        verbose: true
        print-hash: true
